name: IIIT Notebook
permalink: /:title:output_ext
collections:
    courses:
      output: true
    notes:
      output: true

markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "notes"
      is_note: true
  - scope:
      path: ""
    values:
      layout: "default"
